### ISSUE TITLE
Rule against `assert.dom()` with no assertions?

### ISSUE THREAD

**Issue by backspace** [mainmatter/eslint-plugin-qunit-dom#335]
Recently a coworker found calls to `assert.dom` with no actual assertions, which is effectively a no-op, but was probably thought to imply `.exists()`. We discussed the utility of a rule to ensure at least one assertion is made after a `dom` use, before I look further into it (is it even possible?) is that something that would be of interest for this plugin?

Thanks for all the work on `qunit-dom`, I use it all the time! 🤩

**Comment by Turbo87** [comment]
That should be possible and sounds generally useful to me 👍
